config/routes.rb
Rails.application.routes.draw do
  root 'posts#index', as: 'home'

  get 'about' => 'pages#about', as: 'about'

  get 'contact' => 'pages#contact', as: 'contact'

  resources :posts do
    resources :comments

  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
  validates :title, presence: true,
  length: {minimum: 6}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  http_basic_authenticate_with name:"user", password:"user123", only: [:destroy]

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end

  private def comment_params
    params.require(:comment).permit(:username, :body)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
    @title = 'About Us';
    @content = 'The global era of media is changing. It is demanding more of technology than anything. It is really hard to keep up with all of that hence, a medium is a must. We, Tech News Live, have been established putting those values before us that offer to enrich the lives of people and keep them up with technology.

Tech New live is the Leading Tech Review News Portal of Nepal that gives the users information, tools, and advice that will help them decide (with Buy Guides and Tech Guides) get the most out of the Tech. Our company is spread across the internet through our various channel which includes the website itself, Youtube, GooglePlus, Facebook and Twitter.
The global era of media is changing. It is demanding more of technology than anything. It is really hard to keep up with all of that hence, a medium is a must. We, Tech News live Nepal, have been established putting those values before us that offer to enrich the lives of people and keep them up with technology.

Tech News Live is the Leading Tech Review News Portal of Nepal that gives the users information, tools, and advice that will help them decide (with Buy Guides and Tech Guides) get the most out of the Tech. Our company is spread across the internet through our various channel which includes the website itself, Youtube, GooglePlus, Facebook and Twitter.';
  end
  def contact
    @title = 'Contact Us';
    @address = 'Kathmandu, Nepal';
    @phone = '9812226522';
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  http_basic_authenticate_with name:"admin", password:"admin123", except: [:index, :show]
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end
  def new
    @post = Post.new
  end
  def create
    @post =Post.new(post_params)

    if(@post.save)
    redirect_to @post
  else
    render 'new'
  end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if(@post.update(post_params))
    redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to posts_path
  end

  private def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comments.html.erb
<h3>Comments</h3>
<% @post.comments.each do |comment| %>
  <div class="jumbotron">
    <p><strong><%= comment.username %></strong>: <%= comment.body %><%= link_to "X", [comment.post, comment],
                        method: :delete,
                        data: {confirm: 'You really want to delete this Comment?'},
                        :class => '' %>
</p>
  </div>
<% end %>

app/views/comments/_form.html.erb
<h3>Post Comments</h3>
<%= form_for([@post, @post.comments.build]) do |f| %>
<p>
<%= f.label :username %><br>
<%= f.text_field(:username, {:class => 'form-control col-md-8 bg-light'}) %>
</p>
<p>
  <%= f.label :body %><br>
  <%= f.text_area(:body, {:class => 'form-control col-md-8 bg-light'}) %>
</p>

<p>
<%= f.submit({:class => 'btn btn-primary col-md-4'}) %>
</p>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body class="bg-info">
<nav class="navbar navbar-expand-lg navbar-light bg-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
    <a class="navbar-brand text-white " href="#">TECH NEWS LIVE</a>
    <ul class="navbar-nav mr-auto" >
      <li class="nav-item active">
          <%=link_to "Home", home_path %></li>
      <li class="nav-item">
        <a class="" href="#"> &nbsp&nbsp&nbsp </a>
      </li>
      <li class="nav-item">
      <%=link_to "Add News", new_post_path %></li>
      <li class="nav-item">&nbsp&nbsp&nbsp
      <%=link_to "About ", about_path  %></li>
      <li class="nav-item">&nbsp&nbsp&nbsp
      <%=link_to "Contact Us", contact_path %></li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <script >
        (function() {
          var cx = '002042284569810389877:oxua9m3_iaa';
          var gcse = document.createElement('script');
          gcse.type = 'text/javascript';
          gcse.async = true;
          gcse.src = 'https://cse.google.com/cse.js?cx=' + cx;
          var s = document.getElementsByTagName('script')[0];
          s.parentNode.insertBefore(gcse, s);
        })();
      </script>
      <gcse:search></gcse:search>
    </form>
  </div>
</nav>

  <div class="container">
        <%= yield %>
  </div>
  </body>
</html>

app/views/pages/about.html.erb
<br><br><br><br><br>
<h1 class="text-light"><%= @title %></h1>
<p class="text-light text-justify"><%= @content %></p>

app/views/pages/contact.html.erb
<h1 class="text-light"><%= @title %></h1>

<p class="text-light">We are located in Kathnamdu, Nepal</p>
<p class="text-light">Contact us on: 9845563252</p>
<p class="text-light">Email us on: vaskar.1125@gmail.com</p>

<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3532.8141374938928!2d85.317329614538!3d27.69213883276811!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x39eb19b1f2b6d91b%3A0x1dae27974f556d8a!2sTrade+Tower+Nepal!5e0!3m2!1sen!2snp!4v1547488366469" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>

app/views/posts/edit.html.erb
<h1>Update post</h1>
<%= form_for :post, url: post_path(@post), method: :patch do |f| %>
  <% if @post.errors.any? %>
      <% @post.errors.full_messages.each do |msg| %>
        <div class="alert alert-danger"><%= msg %></div>
      <% end %>
    <% end %>
<p>
  <%= f.label :title %><br>
  <%= f.text_field(:title, {:class => 'form-control col-md-8 bg-light'}) %>
</p>
<p>
  <%= f.label :body %><br>
  <%= f.text_area(:body, {:class => 'form-control col-md-8 bg-light'}) %>
</p>
<p>
  <%= f.submit({:class => 'btn btn-success col-md-3'}) %>
</p>
<% end %>

app/views/posts/index.html.erb
<br>
<h2 class="text-center">Read Latest technology related news.</h2>
<% @posts.each do |post| %>
  <div class="jumbotron bg-light">
    <h3 class="text-success"><u><%= post.title %></u></h3>
    <p><%= post.body %></p>
    <%= link_to "View Comments", post_path(post), :class => 'float-right btn btn-primary' %>

  </div>
<%end%>

app/views/posts/new.html.erb
<br>
<h1 class="text-center">Add New news post.  </h1>
<%= form_for :post, url: posts_path do |f| %>
  <% if @post.errors.any? %>
      <% @post.errors.full_messages.each do |msg| %>
        <div class="alert alert-danger"><%= msg %></div>
      <% end %>
    <% end %>
    <div class="">
      <p>
        <%= f.label :title %><br>
        <%= f.text_field(:title, {:class => 'form-control col-md-8 bg-light'}) %>
      </p>
      <p>
        <%= f.label :body %><br>
        <%= f.text_area(:body, {:class => 'form-control col-md-8 bg-light'}) %>
      </p>
      <p>
        <%= f.submit({:class => 'btn btn-success col-md-3'}) %>
      </p>
      <% end %>
    </div>

app/views/posts/show.html.erb
<br>
<%= render 'comments/form'%>
<hr>
<%= render 'comments/comments'%>
<h2><%= @post.title %></h2>
<p><%= @post.body%></p>
<br>

<%= link_to "Edit", edit_post_path(@post), :class => 'btn btn-success col-md-1' %>
<%= link_to "Delete", post_path(@post),
                    method: :delete,
                    data: {confirm: 'You really want to delete this posts?'},
                    :class => 'btn btn-danger col-md-1' %>